### DISCUSSION TITLE
Create slack bot deployment for kubernetes

### DISCUSSION THREAD

**Discussion by humanzai** [innogames/slack-bot#359] [Show and tell]
### **Create** k8s deployment:
I hope it will help someone :)

1. Create persistentvolume and persistantvolumeclaim:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slack-dev-bot-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkins
  name: slack-dev-bot-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
```
2. Create ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-dev-bot-config
  namespace: jenkins
  labels:
    k8s-app: slack-dev-bot
data: 
   config.yaml: |-
    slack:
      token: xoxb-xxxxx
      socket_token: xapp-xxxx
      debug: false # some more slack debug information

    allowed_users: {}
    admin_users: {}
    commands: 

    # Jenkins example: "deploy feature-1234" will build clients, deploy it and prints a link after success.
     - name: Build Frontend dev | (fe [branch] [env])
       trigger: "fe (?P<BRANCH>[\\w\\d\\-_\\.\\/]+) (?P<ENV>[\\w\\d\\-_\\.\\/]+)"
       commands:
         - "trigger job Frontend {{.BRANCH}} {{.ENV}}"
         - "add reaction :white_check_mark:"

    # optional Jenkins integration
    jenkins:
      host: https://jenkins.dev
      username: user
      password: pass
      jobs:
        Frontend: 
          parameters:
           - name: BRANCH
             default: develop
             type: branch
           - name: ENV
             default: dev

    logger:
      level: info
      file: ./bot.log

    timezone: UTC

```
3. Create Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-dev-bot
  labels:
    k8-app: slack-dev-bot
  namespace: jenkins  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: slack-dev-bot
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: slack-dev-bot
    spec:
      containers:
        - args: ["-config", "/config.yaml"]
          command: ["./app"]
          image: brainexe/slack-bot:latest
          name: slack-dev-bot
          volumeMounts:
            - mountPath: /config.yaml
              name: slack-dev-bot-config
              subPath: config.yaml
            - mountPath: /storage
              name: slack-dev-bot-data
      restartPolicy: Always
      volumes:  
      - name: slack-dev-bot-config
        configMap:
          defaultMode: 0640
          name: slack-dev-bot-config
      - name: slack-dev-bot-data
        persistentVolumeClaim:
          claimName: slack-dev-bot-data
```
