### ISSUE TITLE
List of simple jobs returns: no job defined in config

### ISSUE THREAD

**Issue by rkirimov** [innogames/slack-bot#418]
## Describe the problem

When I configure a list of simple jobs without parameters, it fails with `no job defined in config: jenkins.jobs`. Running with `-show-config` option returns

```
jenkins:
    host: https://jenkins.example.com
    username: my_user
    password: 123
    jobs: {}
```

config.yaml

```
jenkins:
  host: https://jenkins.example.com
  username: my_user
  password: 123
  jobs:
    JOB1:
    JOB2:
```

If I add `parameters` or `trigger` field, for example, the jobs are parsed correctly and I'm able to trigger the jobs.

I tried something like 

```
jenkins:
  jobs:
    JOB1: {}
    JOB2: {}
```

But with the same result.
