### ISSUE TITLE
Ability to trigger multibranch pipelines

### ISSUE THREAD

**Issue by rkirimov** [innogames/slack-bot#419]
Have you had any success working with multibranch pipelines? We have some that build per-branch and per-PR. So, I was curious if it'd be possible to add support for multibranch pipeline in here.

I came across [this](https://github.com/bndr/gojenkins/issues/248) issue which is what I experienced as well but even when providing the correct name, it fails with 404 error.

config.yaml

```
jenkins:
  jobs:
    deployer/job/main:
      foo: bar
```
